SUPPORTED_LOCALES = ["tr-TR", "en-US"]
DEFAULT_LOCALE = "tr-TR"

MAX_QUESTIONS_PER_GENERATION = 50
MAX_UPLOAD_SIZE_MB = 50
ALLOWED_DOCUMENT_TYPES = [".pdf", ".docx", ".txt"]

MCQ_MIN_OPTIONS = 4
MCQ_MAX_OPTIONS = 6

AUTOSAVE_DEBOUNCE_MS = 2000
INTEGRITY_EVENT_BATCH_INTERVAL_MS = 10000

IRT_INITIAL_THETA = 0.0
IRT_THETA_SE_THRESHOLD = 0.3
IRT_MAX_QUESTIONS = 50
IRT_MIN_QUESTIONS = 10

LLM_CONFIDENCE_THRESHOLD = 0.7
LLM_REGRADE_CONFIDENCE_THRESHOLD = 0.5
